{{- if (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
apiVersion: v1
metadata:
  name: ibm-wh-acd-ce-certs-truststore-pem
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app.kubernetes.io/name: ibm-wh-acd-ce-certs-truststore-pem
    app.kubernetes.io/instance: ibm-wh-acd-ce-certs-truststore-pem-{{ .Release.Name }}
    helm.sh/chart: ibm-wh-acd-chart
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/version: "2.0.0"
data:
kind: ConfigMap
{{- end }}
